---
abstract: 'Feature-rich REST controller for use with ExtJS'
author:
  - 'Moritz Onken <onken@netcubed.de>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.011, CPAN::Meta::Converter version 2.133380'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-ExtJS-REST
provides:
  CatalystX::Action::ExtJS::REST:
    file: lib/CatalystX/Action/ExtJS/REST.pm
    version: v2.1.3
  CatalystX::Controller::ExtJS::REST:
    file: lib/CatalystX/Controller/ExtJS/REST.pm
    version: v2.1.3
  CatalystX::ExtJS::REST:
    file: lib/CatalystX/ExtJS/REST.pm
    version: v2.1.3
requires:
  Catalyst::Action::REST: 0.88
  Catalyst::Action::RenderView: 0
  Catalyst::Runtime: 5.80024
  CatalystX::ExtJS::Direct: v2.1.5
  DBIx::Class: 0.08127
  HTML::Entities: 0
  HTML::FormFu::ExtJS: 0
  HTML::FormFu::Model::DBIC: 0.08
  JavaScript::Dumper: 0.011
  Lingua::EN::Inflect: 0
  Moose: 1.21
  Path::Class: 0
  Try::Tiny: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CatalystX-ExtJS-REST
  homepage: http://search.cpan.org/dist/CatalystX-ExtJS-REST/
  repository: git://github.com/monken/p5-catalystx-extjs-rest.git
version: 2.1.3
x_Dist_Zilla:
  perl:
    version: 5.018002
  plugins:
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.011
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 5.011
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.10
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 5.011
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: PruneFiles
      version: 5.011
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 5.011
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: 5.011
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 5.011
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 5.011
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.006
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.006
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: 4.006
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: 4.006
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: 4.006
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: 4.006
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: 4.006
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: 4.006
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: 4.006
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: 4.006
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: 4.006
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: 4.006
      name: PodWeaver
      version: 4.005
    -
      class: Dist::Zilla::Plugin::Prepender
      name: Prepender
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 5.011
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: ShareDir
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: Bugtracker
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: Homepage
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: 0.19
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package: {}
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: 1
          inherit_version: 1
          meta_noindex: 1
      name: MetaProvides::Package
      version: 1.15000002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 5.011
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 5.011
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 5.011
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 5.011
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Readme
      name: Readme
      version: 5.011
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 5.011
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.011
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
      version: 5.011
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.011
